const res = {
  Title: "Ocean's Thirteen",
  Year: "2007",
  Rated: "PG-13",
  Released: "08 Jun 2007",
  Runtime: "122 min",
  Genre: "Crime, Thriller",
  Director: "Steven Soderbergh",
  Writer: "Brian Koppelman, David Levien, George Clayton Johnson",
  Actors: "George Clooney, Brad Pitt, Matt Damon",
  Plot: "Danny Ocean rounds up the boys for a third heist after casino owner Willy Bank double-crosses one of the original eleven, Reuben Tishkoff.",
  Language: "English, Mandarin, Spanish, French",
  Country: "United States",
  Awards: "1 win & 5 nominations",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BMTMyNTc1NzY5MV5BMl5BanBnXkFtZTcwNDM4NTQzMw@@._V1_SX300.jpg",
  Ratings: [
    { Source: "Internet Movie Database", Value: "6.9/10" },
    { Source: "Rotten Tomatoes", Value: "70%" },
    { Source: "Metacritic", Value: "62/100" },
  ],
  Metascore: "62",
  imdbRating: "6.9",
  imdbVotes: "341,327",
  imdbID: "tt0496806",
  Type: "movie",
  DVD: "13 Nov 2007",
  BoxOffice: "$117,154,724",
  Production: "N/A",
  Website: "N/A",
  Response: "True",
};
