// Next Modules
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// Components
import { Flex, Text } from "@chakra-ui/react";
import Footer from "../components/Footer";
import MovieList from "../components/MovieList/MovieList";

// Functions
import { fetchMovieList } from "../lib/movies";
import { updateDatabase } from "../lib/build";

// Static Prop Generation
export async function getStaticProps() {
  updateDatabase(); // Update Airtable records on build

  const movieList = await fetchMovieList();
  return {
    props: {
      movies: movieList,
    },
  };
}

export default function Home({ movies }) {
  // console.log(movies[0]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {!movies ? (
          <Flex>
            <Text>Loading Movies...</Text>
          </Flex>
        ) : (
          <MovieList movies={movies} />
        )}
      </main>

      <Footer />
    </div>
  );
}
